no_tracing decorator
mirumee/saleor pull request #6891
Opened 2021-02-15 12:18 UTC by tomaszszymanski129

I want to merge this change because it adds `no_tracing` decorator which allows to skip tracing of simple resolvers we don't want.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2021-02-26 11:28 UTC, tomaszszymanski129 commented on saleor/core/tracing.py
> +        setattr(info.context, NO_TRACE_ATTR, True)
investigated and this propagates to other fields after first decorated field is resolved, will have to be changed.

2021-03-04 11:47 UTC, patrys commented
Task linked: [SALEOR-2157 Add no_tracing decorator to resolvers](https://app.clickup.com/t/2549495/SALEOR-2157)

2021-03-08 12:09 UTC, fowczarek requested changes
I found a bug. 
My query:
```
{
  user(id: "VXNlcjo5NDI=") {
    id
    events {
      id
      message
      count
      user {
        email
      }
      orderLine{
        id
      }
    }
  }
}
```
User have 2 events assigned with `parameters`:
```
{
    "message": "aaa",
    "count": 5,
    "order_line_pk": 1
}
```

For your branch, I got 1 span for `CustomerEvent.message` but 0 spans for `CustomerEvent.orderLine` and `CustomerEvent.user` 
![image](https://user-images.githubusercontent.com/43955230/110319092-ade07d00-800e-11eb-8718-7d5497dda9d1.png)

For master, I got 2 spans for `CustomerEvent.message`, `CustomerEvent.count`,  `CustomerEvent.orderLine` and `CustomerEvent.user` 
![image](https://user-images.githubusercontent.com/43955230/110319440-30693c80-800f-11eb-92a1-982ca5003cd8.png)


After your changes, we should receive 2 spans for `CustomerEvent.orderLine`, `CustomerEvent.user` 

To reproduce this case you should add

2021-03-29 11:35 UTC, tomaszszymanski129 commented
As discussed days ago, this will have to be handled different way, closing this one for now.

2021-03-29 11:35 UTC, closed without merging