Add description to shipping method
mirumee/saleor pull request #7116
Opened 2021-04-07 07:36 UTC by IKarbowiak

- Extend the `ShippingMethod` model with `description`.
- Extend the `ShippingMethod` type with `description` field.
- Extend mutation to add/edit description: `shippingPriceUpdate`, `shippingPriceCreate`.
- Support translating `ShippingMethod` `description`.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2021-04-07 07:36 UTC, patrys commented
Task linked: [SALEOR-2821 Add description to shipping method](https://app.clickup.com/t/2549495/SALEOR-2821)

2021-04-07 11:54 UTC, d-wysocki approved these changes

2021-04-08 06:47 UTC, maarcingebala approved these changes

2021-04-08 06:48 UTC, maarcingebala commented
Needs to wait for dashboard changes.

2021-04-12 10:13 UTC, korycins commented on CHANGELOG.md
> +- Add description to shipping method - #7116 by @IKarbowiak
It looks like, we are changing an API a little bit here. Don't we want to add more details to changelog? Also, shouldn't be placed in breaking changes (I see that some types of input have been renamed/extended?

2021-04-12 12:30 UTC, fowczarek approved these changes

2021-04-12 12:30 UTC, fowczarek commented on saleor/graphql/translations/mutations.py
> +    description = graphene.JSONString()
Maybe?
```suggestion
    description = graphene.JSONString(description="Translated shipping method description (JSON).")
```

2021-04-13 11:44 UTC, jwm0 requested changes
Missing `description` field on `ShippingMethodTranslatableContent`

2021-04-15 08:50 UTC, jwm0 requested changes

2021-04-15 08:50 UTC, jwm0 commented on saleor/graphql/schema.graphql
> +  shippingPriceTranslate(id: ID!, input: DescriptionTranslationInput!, languageCode: LanguageCodeEnum!): ShippingPriceTranslate
`DescriptionTranslationInput` name does not make sense, I suggest `ShippingPriceTranslationInput`

2021-04-15 13:01 UTC, jwm0 approved these changes

2021-04-16 12:16 UTC, merged