Validate product has variants
mirumee/saleor pull request #7459
Opened 2021-06-10 09:36 UTC by d-wysocki

I want to merge this change because...I want to validate if product_type has flag `has_variant` set to false.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2021-06-10 09:36 UTC, patrys commented
Task linked: [SALEOR-2873 Do not allow creating variant on product with product type that has `hasVariants` field set to False](https://app.clickup.com/t/2549495/SALEOR-2873)

2021-06-10 12:52 UTC, IKarbowiak approved these changes

2021-06-10 12:52 UTC, IKarbowiak commented on saleor/graphql/product/mutations/products.py
> +            raise ValidationError({"attributes": exc})
I see that `clean_input` is quite long. Maybe we can separate this to another function.

2021-06-11 08:31 UTC, tomaszszymanski129 approved these changes

2021-06-11 11:20 UTC, maarcingebala requested changes

2021-06-11 11:32 UTC, closed without merging