Gift card bulk deactivate mutation
mirumee/saleor pull request #7782
Opened 2021-08-06 11:08 UTC by tomaszszymanski129

I want to merge this change because it adds new mutation - `giftCardBulkDeactivate`.

⚠️ This is a PR to feature branch.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2021-08-06 11:08 UTC, patrys commented
Task linked: [SALEOR-3881 Add giftCardBulkDeactivate mutation](https://app.clickup.com/t/2549495/SALEOR-3881)

2021-08-09 08:19 UTC, maarcingebala approved these changes

2021-08-09 08:39 UTC, IKarbowiak requested changes

2021-08-09 08:39 UTC, IKarbowiak commented on saleor/graphql/giftcard/bulk_mutations.py
> +        queryset.update(is_active=True)
👮‍♂️ 🚔 
```
    queryset.update(is_active=False)
```

2021-08-09 08:39 UTC, IKarbowiak commented on saleor/graphql/giftcard/tests/mutations/test_gift_card_bulk_deactivate.py
> +    assert data["count"] == len(ids)
IMO we should also check if gift cards havebeen deactivated.

2021-08-09 08:41 UTC, fowczarek requested changes

2021-08-09 08:41 UTC, fowczarek commented on saleor/graphql/giftcard/bulk_mutations.py
> +        queryset.update(is_active=True)
:police_car: 
```suggestion
        queryset.update(is_active=False)
```

2021-08-09 08:41 UTC, fowczarek commented on saleor/graphql/giftcard/bulk_mutations.py
> +        gift_card_ids = [gift_card.id for gift_card in queryset]
Maybe?
```suggestion
        gift_card_ids = queryset..values_list("id", flat=True)
```

2021-08-09 08:41 UTC, fowczarek commented on saleor/graphql/giftcard/tests/mutations/test_gift_card_bulk_deactivate.py
> +def test_gift_card_bulk_deactivate_by_staff(
This test should also check that these gift cards are deactivated after this mutation.

2021-08-09 08:41 UTC, fowczarek commented on saleor/graphql/giftcard/tests/mutations/test_gift_card_bulk_deactivate.py
> +def test_gift_card_bulk_deactivate_by_app(
This test should also check that these gift cards are deactivated after this mutation.

2021-08-09 08:58 UTC, tomaszszymanski129 commented on saleor/graphql/giftcard/bulk_mutations.py
> +        gift_card_ids = [gift_card.id for gift_card in queryset]
later qs evaluation breaks if we do so

2021-08-09 08:59 UTC, fowczarek approved these changes

2021-08-09 09:04 UTC, IKarbowiak approved these changes

2021-08-09 09:22 UTC, merged